import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "İlk Next.js projesi",
  description: "Generated by Semih Sahinoglu",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body>{children}</body>
    </html>
  );
}
